name: examen2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # ESTADO Y ARQUITECTURA (Clean Architecture)
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  get_it: ^9.2.0
  dartz: ^0.10.1
  
  # BACKEND - SUPABASE
  supabase_flutter: ^2.12.0
  flutter_dotenv: ^6.0.0
  
  # FIREBASE (version exactas compatibles)
  firebase_core: ^3.8.0
  firebase_analytics: ^11.3.2
  firebase_crashlytics: ^4.3.10
  
  # GEOLOCALIZACIÓN Y MAPAS
  geolocator: ^14.0.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  http: ^1.6.0
  
  # NOTIFICACIONES
  flutter_local_notifications: ^19.5.0
  
  # PERMISOS
  permission_handler: ^12.0.1
  
  # IMÁGENES Y MULTIMEDIA
  image_picker: ^1.2.1
  cached_network_image: ^3.4.1
  
  # ALMACENAMIENTO LOCAL
  shared_preferences: ^2.5.4
  
  # UI Y UTILIDADES
  intl: ^0.20.2
  shimmer: ^3.0.0
  table_calendar: ^3.2.0
  uuid: ^4.5.2
  go_router: ^14.3.0
  provider: ^6.1.2
  animations: ^2.0.9
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/Logo_app.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Logo_app.png"

  # Opcional recomendado para Android 12+ (Adaptive Icon)
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/Logo_app.png"
